# image will be published to ghcr.io/<user>/<name>
name: fw13-amd-kinoite
# description will be included in the image's metadata
description: My customized version of Kinoite for the FW13 AMD

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - starship
      - powertop
      - tailscale
      - fprintd
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - android-udev-rules
      - nvtop

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
                  # in your custom.just (added by default) or local justfile
      - ublue-os-wallpapers
      
  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      - Celluloid: io.github.celluloid_player.Celluloid
      - Krita: org.kde.krita
      - mpv: io.mpv.Mpv
      - Flatseal: com.github.tchx84.Flatseal
      - OBSStudio: com.obsproject.Studio
      - Obsidian: md.obsidian.Obsidian
      - Signal: org.signal.Signal
      - Telegram: org.telegram.desktop
      - Audacity: org.audacityteam.Audacity
      - VSCodium: com.vscodium.codium
      - Handbrake: fr.handbrake.ghb
      - PikaBackup: org.gnome.World.PikaBackup

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - rpm_ostree_install.sh
      - signing.sh
